Repository imas/imasbook, pull requests merged in 2019-03, with the labels that each got.

#45 目次・あとがきのスタイル調整
  imasbook02/templates/assets/css/atogaki.css
  imasbook02/templates/assets/css/toc.css
  imasbook02/templates/assets/img/crssnky.png
  imasbook02/templates/assets/img/mh35.png
  imasbook02/templates/index.html
Labels: スタイル修正

#46 URLリンクの下線削除
  imasbook02/templates/assets/css/main.css
Labels: スタイル修正

#44 footnoteがあると画像がセンタリングされない問題の対処
  imasbook02/Gruntfile.js
  imasbook02/templates/assets/css/main.css
Labels: スタイル修正

#34 何つながりなのかな？を探る自然言語処理
  imasbook02/articles/images/takemikami/figure01.png
  imasbook02/articles/images/takemikami/figure02.png
  imasbook02/articles/images/takemikami/figure03.png
  imasbook02/articles/images/takemikami/figure04.png
  imasbook02/articles/images/takemikami/figure05.png
  imasbook02/articles/takemikami.md
  imasbook02/templates/assets/img/takemikami.png
  imasbook02/templates/index.html
Labels: 原稿

#35 MH35の原稿 Heroku+Railsでコンベンションセンターもどきを作ってみた
  imasbook02/articles/images/mh35/.keep
  imasbook02/articles/images/mh35/app_top.png
  imasbook02/articles/images/mh35/no_apps_screen.png
  imasbook02/articles/images/mh35/provision_herokupg.png
  imasbook02/articles/images/mh35/top_screen.png
  imasbook02/articles/mh35.md
Labels: 原稿

#36 CircleCIに本日が誕生日のアイドルを出力させて生産性を上げる
  imasbook02/articles/images/yutagoto/.DS_Store
  imasbook02/articles/images/yutagoto/config.png
  imasbook02/articles/images/yutagoto/config21.png
  imasbook02/articles/images/yutagoto/discord.png
  imasbook02/articles/images/yutagoto/setup_circleci.png
  imasbook02/articles/images/yutagoto/slack.png
  imasbook02/articles/images/yutagoto/stdout.png
  imasbook02/articles/yutagoto.md
  imasbook02/templates/assets/img/yutagoto.png
  imasbook02/templates/index.html
Labels: 原稿

#41 im@sparql応用 〜UE4編〜
  imasbook02/articles/crssnky.md
  imasbook02/articles/images/crssnky/.keep
  imasbook02/articles/images/crssnky/BP.png
  imasbook02/articles/images/crssnky/BP2.png
  imasbook02/articles/images/crssnky/BP3.png
  imasbook02/articles/images/crssnky/BPcreate.png
  imasbook02/articles/images/crssnky/BPcreate2.png
  imasbook02/articles/images/crssnky/save_and_compile.png
  imasbook02/articles/images/crssnky/save_and_compile2.png
  imasbook02/config.json
  imasbook02/templates/index.html
Labels: 原稿

#42 アイマスを「証明」してみる話
  imasbook02/articles/images/kiridaruma/window.png
  imasbook02/articles/kiridaruma.md
  imasbook02/templates/index.html
Labels: 原稿

#43 増え続けるアイマス楽曲を一括管理
  imasbook02/articles/images/wakuwakup/01.jpg
  imasbook02/articles/images/wakuwakup/02.jpg
  imasbook02/articles/images/wakuwakup/03.jpg
  imasbook02/articles/images/wakuwakup/04.jpg
  imasbook02/articles/images/wakuwakup/05.jpg
  imasbook02/articles/wakuwakup.md
  imasbook02/templates/assets/img/wakuwakup.jpg
  imasbook02/templates/index.html
Labels: 原稿

#37 うづコインを支える技術
  imasbook02/articles/images/kagemiku/evans_ss.png
  imasbook02/articles/images/kagemiku/uzucoin_slide.png
  imasbook02/articles/images/kagemiku/uzuki_chain.png
  imasbook02/articles/kagemiku.md
  imasbook02/templates/assets/img/kagemiku.png
  imasbook02/templates/index.html
Labels: 原稿

#40 ｢アイドルマスター シンデレラガールズ｣のデータに対するスリーレターコードを利用したユニークなインデックスの提案
  imasbook02/articles/papix.md
  imasbook02/templates/index.html
Labels: 原稿

#49 何つながりなのかな？を探る自然言語処理の誤字修正
  imasbook02/articles/takemikami.md
Labels: 原稿

#48 imasbook02 最終調整
  imasbook02/articles/crssnky.md
  imasbook02/articles/kiridaruma.md
  imasbook02/articles/mh35.md
  imasbook02/articles/yutagoto.md
  imasbook02/config.json
  imasbook02/templates/index.html
Labels: スタイル修正, 原稿
